export default {
  USER_REGISTER: "USER REGISTER",
  USER_LOGIN: "USER LOGIN",
  USER_LOGIN_BY_GOOGLE: "USER LOGIN BY GOOGLE",
  GET_ALL_USERS: "GET ALL USER",
  GET_USER_BY_ID: "GET USER BY ID",
  UPDATE_USER_BY_ID: "UPDATE USER BY ID",
  DELETE_USER_BY_ID: "DELETE USER BY ID",

  // videos

  CREATE_VIDEO: "CREATE VIDEOS",
  GET_VIDEOS: "GET VIDEOS",
  GET_VIDEOS_BY_RANDOM: "GET VIDEOS BY RANDOM",
  GET_VIDEO_BY_ID: "GET VIDEO BY ID",
  UPDATE_VIDEO_BY_ID: "UPDATE VIDEO BY ID",
  DELETE_VIDEO_BY_ID: "DELETE VIDEO BY ID",
  ADD_VIEW_VIDEO_BY_ID: "ADD VIEW VIDEO BY ID",
  TREND_VIDEOS: "TREND VIDEOS",

  // likes and desLikes

  ADD_LIKE: "ADD LIKE",
  DELETE_LIKE: "DELETE LIKE",
  GET_LIKES_IN_VIDEO: "GET LIKES IN VIDEO",
  ADD_DESLIKE: "ADD DESLIKE",
  DELETE_DESLIKE: "DELETE DESLIKE",
  GET_DESLIKES_IN_VIDEO: "GET DESLIKES IN VIDEO",

  // comments

  ADD_COMMENT: "ADD COMMENT",
  UPDATE_COMMENT: "UPDATE COMMENT",
  DELETE_COMMENT: "DELETE COMMENT",
  GET_COMMENTS_IN_VIDEO: "GET COMMENTS IN VIDEO",
  GET_COMMENT: "GET COMMENT",
};
