export default {
  USER_REGISTER: "USER REGISTER",
  USER_LOGIN: "USER LOGIN",
  USER_LOGIN_BY_GOOGLE: "USER LOGIN BY GOOGLE",
  GET_ALL_USERS: "GET ALL USER",
  GET_USER_BY_ID: "GET USER BY ID",
  UPDATE_USER_BY_ID: "UPDATE USER BY ID",
};
